---
- name: Deploy web-site
  hosts: do
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python
#  vars_prompt:
#    - name: commit
#      prompt: "What is the commit name?"
#      private: no

  tasks:
    - name: stop service
      shell: systemctl stop itblog
      become: yes

        #    - name: git push
        #      delegate_to: localhost
        #      shell: git add -A && git commit -m "{{ commit }}" ; git push origin master

        #    - name: git pull
        #      shell: cd /home/tabula/denisbakhtin/itblog && git pull origin master

    - name: build new binary
      delegate_to: localhost
      shell: cd /home/tabula/dart/itblog && make release

    - name: clean old binaries
      shell: cd /home/tabula/itblog && rm -f main

    - name: copy binary to remote host
      copy:
        src: /home/tabula/dart/itblog/lib/main
        dest: /home/tabula/itblog/main

    # too slow
    #- name: copy assets to remote host
    #  copy:
    #    src: /home/tabula/dart/itblog/lib/public/assets
    #    dest: /home/tabula/itblog/lib/public/

    - name: copy config.json to remote host
      copy:
        src: /home/tabula/dart/itblog/lib/config.json
        dest: /home/tabula/itblog/lib/config.json

    - name: copy application.js to remote host
      copy:
        src: /home/tabula/dart/itblog/lib/public/assets/application.js
        dest: /home/tabula/itblog/lib/public/assets/application.js

    - name: copy application.css to remote host
      copy:
        src: /home/tabula/dart/itblog/lib/public/assets/application.css
        dest: /home/tabula/itblog/lib/public/assets/application.css

    - name: mark binary as executable
      shell: cd /home/tabula/itblog && chmod +x main

    - name: start service
      shell: systemctl start itblog
      become: yes
