name: itblog
description: My IT blog
version: 0.0.2
author: Denis Bakhtin <denis.bakhtin@gmail.com>
homepage: https://github.com/denisbakhtin/itblog-dart

environment:
  sdk: ">=2.12.0 <3.0.0" 

dependencies:
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  path:
dev_dependencies:
  json_serializable: ^4.0.3
  build_runner: ^1.12.2
  injector: ^2.0.0
  test:
  mockito:
