name: itblog
description: My IT blog
version: 0.0.2
homepage: https://github.com/denisbakhtin/itblog-dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
<<<<<<< HEAD
  shelf: ^1.1.1
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  shelf_secure_cookie: ^1.2.0 
  path:
  sqlite3: ^1.1.0
=======
  shelf: ^1.2.0 
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  shelf_secure_cookie: ^1.2.0 
  path: 
  sqlite3: ^1.3.1
>>>>>>> sass
  translit: ^2.0.0
  crypto: ^3.0.1
  mime: ^1.0.1
  args: ^2.3.0
  shelf_body_parser:
    git: https://github.com/denisbakhtin/shelf_body_parser
<<<<<<< HEAD
  args: ^2.3.0
=======
  html: ^0.15.0
  shelf_hotreload: ^1.0.0
>>>>>>> sass

dev_dependencies:
  build_runner: ^2.1.5 
  injector: ^2.0.0
  test:
  dirk:
    git: https://github.com/denisbakhtin/dirk
