version: '3'

tasks:
  default:
    cmds:
      - task: watch

  test:
    cmds:
      - pub run --no-sound-null-safety test

  run:
    cmds:
      - pub run --no-sound-null-safety lib/main.dart

  watch:
    sources:
      - ./**/*.dart

    cmds:
      - pub run --no-sound-null-safety lib/main.dart


